name: Build & Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # 1. Windows (x64)
          - os: windows-latest
            name: Windows
            
          # 2. Mac Intel (Garante que o Chromium baixado seja Intel)
          - os: macos-13 
            name: macOS Intel
            
          # 3. Mac ARM/M1 (Garante que o Chromium baixado seja ARM)
          - os: macos-latest
            name: macOS ARM

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        # Aqui a m√°gica acontece: 
        # No 'macos-13' ele baixa Chromium Intel. 
        # No 'macos-latest' ele baixa Chromium ARM.
        run: npm install

      - name: Build & Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish